language: bash
sudo: required

before_script:
  - chmod +x *.sh
  - ./install.sh

script:
  - ./shebang.sh
  - ./shebang.sh update
  - ./shebang.sh keesvv/shebang master

after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  cd kcov-master &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  sudo make install &&
  cd ../.. &&
  rm -rf kcov-master &&
  mkdir -p coverage &&
  kcov coverage shebang.sh &&
  bash <(curl -s https://codecov.io/bash)
